-- ═══════════════════════════════════════════════════════════════════════════
-- MIGRAÇÃO MULTI-TENANT — Toca Estoque -> Plataforma
-- Aplicada em produção em 05/08/2026 (via mcp__supabase__apply_migration,
-- nome da migração: migracao_multi_tenant_producao_v1). Backup completo de
-- todas as 18 tabelas feito antes, no schema backup_pre_multitenant_20260805.
--
-- Idempotente onde possível (IF NOT EXISTS / ON CONFLICT). Testada primeiro
-- contra um projeto Supabase isolado antes de qualquer aplicação em produção,
-- e depois validada ao vivo contra o schema mt com o app rodando de verdade.
-- ═══════════════════════════════════════════════════════════════════════════

-- 1) Permite o papel 'superadmin' (administra a PLATAFORMA, não um restaurante)
alter table users drop constraint if exists users_role_check;
alter table users add constraint users_role_check
  check (role = any (array['admin'::text, 'gerente'::text, 'operador'::text, 'superadmin'::text]));

-- 2) Tabela de restaurantes (tenants)
create table if not exists tenants (
  id bigint generated by default as identity primary key,
  nome text not null,
  slug text not null unique,
  cnpj text,
  telefone text,
  endereco text,
  plano text not null default 'financeiro' check (plano in ('financeiro','estoque','completo')),
  config jsonb not null default '{}'::jsonb,
  ativo boolean not null default true,
  suspenso_em timestamptz,
  criado_em timestamptz not null default now()
);

-- 3) Catálogo-modelo (produtos_modelo) -- vem dos produtos REAIS do Toca, sem
-- preço/quantidade, pra restaurante novo nascer pronto em vez de vazio.
create table if not exists produtos_modelo (
  id bigint generated by default as identity primary key,
  nome text not null,
  categoria text not null,
  unidade text not null
);

-- 4) Restaurante 1 = Toca do Coelho (o restaurante real, dono de todo dado existente)
insert into tenants (id, nome, slug, plano, ativo)
values (1, 'Restaurante Toca do Coelho', 'toca-do-coelho', 'completo', true)
on conflict (id) do nothing;
select setval('tenants_id_seq', greatest((select max(id) from tenants), 1));

-- 5) Semeia o catálogo-modelo a partir do catálogo real do Toca (exclui produto
-- de teste do robô de QA -- não faz sentido sugerir isso pra restaurante novo).
insert into produtos_modelo (nome, categoria, unidade)
select nome, categoria, unidade from produtos
where ativo = 1 and nome !~* '^(qa|robo|teste|test)\b'
on conflict do nothing;

-- 6) tenant_id nas 17 tabelas de dado + users (nullable no users: superadmin
-- não tem restaurante fixo). NULLABLE primeiro, backfill, depois trava.
do $$
declare
  t text;
  tabelas text[] := array[
    'produtos','categorias','movimentacoes','fechamentos_diarios','pagamentos_comprovantes',
    'conta_pendencias','conta_memoria','nota_pendencias','sinonimos','inventarios',
    'inventario_itens','audit_logs','backups_estoque','cardapios_salvos','ia_agenda',
    'pratos_cardapio','snapshots_diarios'
  ];
begin
  foreach t in array tabelas loop
    execute format('alter table %I add column if not exists tenant_id bigint', t);
    execute format('update %I set tenant_id = 1 where tenant_id is null', t);
    execute format('alter table %I alter column tenant_id set not null', t);
    execute format('alter table %I add constraint %I foreign key (tenant_id) references tenants(id)', t, t || '_tenant_id_fkey');
    execute format('create index if not exists %I on %I (tenant_id)', 'idx_' || t || '_tenant_id', t);
  end loop;
end $$;

-- users: NULLABLE de propósito (superadmin não tem restaurante fixo)
alter table users add column if not exists tenant_id bigint;
update users set tenant_id = 1 where tenant_id is null and role <> 'superadmin';
alter table users add constraint users_tenant_id_fkey foreign key (tenant_id) references tenants(id);
create index if not exists idx_users_tenant_id on users (tenant_id);

-- 7) As 4 unicidades que precisam virar (tenant_id, coluna) -- sem isso, o 2º
-- cliente não pode ter "Hortifruti", nem produto de nome igual ao de outro,
-- nem fechar o mesmo dia que o primeiro cliente já fechou.
alter table categorias drop constraint if exists categorias_nome_key;
alter table categorias add constraint categorias_tenant_nome_key unique (tenant_id, nome);

alter table fechamentos_diarios drop constraint if exists fechamentos_diarios_data_key;
alter table fechamentos_diarios add constraint fechamentos_diarios_tenant_data_key unique (tenant_id, data);

alter table produtos drop constraint if exists produtos_nome_key;
alter table produtos add constraint produtos_tenant_nome_key unique (tenant_id, nome);

alter table sinonimos drop constraint if exists sinonimos_termo_key;
alter table sinonimos add constraint sinonimos_tenant_termo_key unique (tenant_id, termo);

-- users_username_key NÃO muda -- username é único na PLATAFORMA (login recebe só
-- usuário+senha, sem saber de qual restaurante; dois "admin" em restaurantes
-- diferentes disputariam a mesma linha).

-- 8) Conta de plataforma (superadmin) -- separada do admin operacional do Toca.
-- Rubens continua com a conta 'admin' de sempre pra tocar o restaurante; esta é
-- só pra abrir/gerenciar clientes novos.
--
-- ATENÇÃO: em produção, essa linha foi inserida com um password_hash real
-- (scrypt salt:hash), gerado uma única vez e comunicado ao Rubens fora deste
-- arquivo -- de propósito, pra não deixar hash de credencial no histórico do
-- git. O placeholder abaixo é só pra deixar claro o formato esperado; rodar
-- este arquivo do zero exige gerar um hash novo (ver hashPassword() em
-- server.js) e substituir SUBSTITUIR_PELO_HASH_REAL antes de aplicar.
insert into users (username, nome, role, password_hash, active, tenant_id)
select 'plataforma', 'Administração da Plataforma', 'superadmin',
       'SUBSTITUIR_PELO_HASH_REAL',
       1, null
where not exists (select 1 from users where username = 'plataforma');
