-- ═══════════════════════════════════════════════════════════════════════════
-- SESSÕES PERSISTIDAS + GRUPOS DE WHATSAPP POR RESTAURANTE
-- Aplicado em produção em 06/08/2026, depois da migração multi-tenant principal
-- (ver SUPABASE_MIGRACAO_MULTI_TENANT.sql). Duas tabelas GLOBAIS (sem tenant_id
-- — ver TABELAS_GLOBAIS em tenant.js), idempotente.
-- ═══════════════════════════════════════════════════════════════════════════

-- 1) Sessões de login no banco em vez de memória do processo. O código já sabia
-- usar isso (createSession/getSession/touchSession/deleteSession em server.js
-- caem pra memória sozinhos se a tabela não existir) — só faltava a tabela.
-- Sem isso, todo deploy derrubava todo mundo logado.
create table if not exists sessions (
  token text primary key,
  user_id bigint not null,
  username text not null,
  nome text,
  role text,
  last_activity timestamptz not null default now()
);
create index if not exists idx_sessions_last_activity on sessions (last_activity);

-- 2) Qual restaurante é dono de qual grupo de WhatsApp. Resolve o tenant a partir
-- do grupo_id (remoteJid) que o n8n manda nos webhooks ler-conta/ler-nota/whatsapp
-- (ver webhookTenantDoGrupo em server.js). Sem grupo cadastrado, cai no Toca do
-- Coelho (tenant 1) — mantém compatibilidade com o bot de sempre.
create table if not exists whatsapp_grupos (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenants(id),
  tipo text not null check (tipo in ('notas','contas')),
  grupo_id text not null unique,
  nome text,
  criado_em timestamptz not null default now()
);
create index if not exists idx_whatsapp_grupos_tenant on whatsapp_grupos (tenant_id);

-- Os 2 grupos que o Toca do Coelho já usava antes de existir essa tabela.
insert into whatsapp_grupos (tenant_id, tipo, grupo_id, nome) values
  (1, 'notas', '120363411729041942@g.us', 'Toca estoque 01'),
  (1, 'contas', '120363411825325691@g.us', 'Toca financeiro')
on conflict (grupo_id) do nothing;
