-- ============================================================================
-- PORCIONAMENTO (queijo, alho...) — v118
-- Contagem diaria de bolas por peso na aba "Realidade do Dia". SO ANOTACAO:
-- nao mexe em movimentacoes nem em produtos. O dado do dia mora dentro de
-- fechamentos_diarios (mesma pegada de pagamentos/cortes/despesas).
--
-- Aditivo e idempotente. NAO derruba nada.
-- Aplicar pela bancada:
--   cd recrutador-web/sql-tests
--   node aplicar.mjs ../../toca-estoque-fix/SUPABASE_PORCIONAMENTO.sql testa-porcionamento.mjs
-- ============================================================================

-- 1. Onde o dia guarda a contagem -------------------------------------------
--    Formato: [ { "item": "Queijo",
--                 "linhas": [ { "peso_g": 40, "tinha": 30, "porcionei": 0, "saiu": 5, "sobrou": 25 }, ... ] },
--               ... ]
--    `sobrou` e recalculado no servidor (tinha + porcionei - saiu); guardado
--    junto so pra o relatorio da semana nao ter que refazer a conta.
ALTER TABLE fechamentos_diarios
  ADD COLUMN IF NOT EXISTS porcionamento JSONB NOT NULL DEFAULT '[]'::jsonb;

-- 2. Config: quais itens e quais pesos de bola --------------------------------
--    tenant_id: mesmo esquema de fechamentos_diarios (inteiro, aponta tenants.id).
--    pesos_g: pesos das bolas em gramas. Queijo {40,150,400}. Alho {1000} (1 kg).
CREATE TABLE IF NOT EXISTS porcionamento_config (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id      BIGINT,
  item           TEXT      NOT NULL,
  pesos_g        INTEGER[] NOT NULL DEFAULT '{}',
  unidade        TEXT      NOT NULL DEFAULT 'bolas',
  ordem          INTEGER   NOT NULL DEFAULT 0,
  ativo          BOOLEAN   NOT NULL DEFAULT true,
  criado_em      TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em  TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_por TEXT
);

-- um item por restaurante (tenant nulo = restaurante base)
CREATE UNIQUE INDEX IF NOT EXISTS porcionamento_config_tenant_item
  ON porcionamento_config (COALESCE(tenant_id, 0), lower(item));

-- 3. RLS + revoke: ninguem pega pela chave publica. O app usa service_role
--    (passa por cima). Sem policy e sem grant = anon/authenticated fora.
ALTER TABLE porcionamento_config ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON porcionamento_config FROM anon, authenticated;

-- 4. Semente: so se ainda nao existir o item (nao sobrescreve ajuste do gerente)
INSERT INTO porcionamento_config (tenant_id, item, pesos_g, unidade, ordem)
SELECT NULL, 'Queijo', ARRAY[40,150,400], 'bolas', 1
WHERE NOT EXISTS (SELECT 1 FROM porcionamento_config WHERE lower(item) = 'queijo');

INSERT INTO porcionamento_config (tenant_id, item, pesos_g, unidade, ordem)
SELECT NULL, 'Alho', ARRAY[1000], 'kg', 2
WHERE NOT EXISTS (SELECT 1 FROM porcionamento_config WHERE lower(item) = 'alho');
